version: 2
updates:
  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: nuget
    rebase-strategy: auto
    schedule:
      interval: daily
  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: github-actions
    rebase-strategy: auto
    schedule:
      interval: daily
  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: pip
    rebase-strategy: auto
    schedule:
      interval: daily
