changelog:
  exclude:
    labels:
      - "whim version"

  categories:
    - title: Documentation 📄
      labels:
        - documentation

    - title: Core
      labels:
        - core
        - "layout engine"

    - title: Runner 🏃🏻
      labels:
        - "runner 🏃🏻"

    - title: Bar
      labels:
        - bar

    - title: Command Palette
      labels:
        - "command palette"

    - title: Floating Layout ☁️
      labels:
        - "floating layout"

    - title: Focus Indicator 👀
      labels:
        - "focus indicator"

    - title: Gaps
      labels:
        - gaps

    - title: Layout Preview
      labels:
        - "layout preview"

    - title: Slice Layout 🍰
      labels:
        - "slice layout"

    - title: Tree Layout 🌳
      labels:
        - "tree layout"

    - title: Updater
      labels:
        - updater

    - title: Other Changes 🖋
      labels:
        - "*"
