name: 🐞 Bug
description: File a bug/issue
labels: ["bug", "triage"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true

- type: textarea
  attributes:
    label: Behavior
    description: A concise description of what you're experiencing, and what you expected to happen.
    placeholder: |
      ### Current behavior
      TODO

      ### Expected behavior
      TODO
  validations:
    required: true

- type: textarea
  attributes:
    label: Config
    description: A `whim.config.csx` that can be used to reproduce the issue.
    placeholder: |
      #r "WHIM_PATH\whim.dll"

      void DoConfig(IConfigContext configContext)
      {
          configContext.WorkspaceManager.Add(CreateWorkspace(configContext, "1"));
          // ...
      }
    render: csharp
  validations:
    required: true

- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **Windows**: Version 21H2 (OS Build 22000.708)
        - **Architecture**: x86_64
        - **Whim**: 0.2.4
    value: |
        - Windows:
        - Architecture:
        - Whim:
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: true

- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
