name: 💡 Feature request
description: Suggest an idea for this project
title: "Title"
labels: ["enhancement"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the feature you would like.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Proposal
    description: A clear and concise description of the feature you would like to see.
  validations:
    required: true
- type: textarea
  attributes:
    label: Alternatives
    description: A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional context
    description: |
      Links? References? Anything that will give us more context about the feature you are suggesting!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
