global using System;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using DotNext;
global using NSubstitute;
global using NSubstitute.ExceptionExtensions;
global using NSubstitute.ReturnsExtensions;
global using Whim.TestUtils;
global using static Whim.TestUtils.StoreTestUtils;
global using Windows.Win32.Foundation;
global using Windows.Win32.Graphics.Gdi;
global using Xunit;
